[2025-04-18]
"求める" = "review"
"選ぶ" = "review"
"行動" = "review"
"本人" = "review"
"持つ" = "review"
"気分" = "review"
"緊張" = "review"
"確認" = "review"
"既に" = "review"
"窓" = "review"
"残念" = "review"
"やっと" = "review"
"残る" = "review"
"痛い" = "review"
"一体" = "review"
"無事" = "review"
"連中" = "review"
"どうしても" = "review"
"黒い" = "review"
"連絡" = "review"
"繰り返す" = "review"
"つく" = "review"
"許す" = "review"
"最近" = "review"
"しばらく" = "review"
"特に" = "review"
"突然" = "review"
"追う" = "review"
"眺める" = "review"
"申し訳ない" = "review"
"伝える" = "review"
"震える" = "review"
"離す" = "review"
"暇" = "review"
"生きる" = "review"
"頂く" = "review"
"済む" = "review"
"回る" = "review"
"夏" = "review"
"あいつ" = "review"
"きっと" = "review"
"黙る" = "review"
"疲れる" = "review"
"方" = "review"
"他" = "review"
"結婚" = "review"
"出会う" = "review"
"今夜" = "review"
"よく" = "review"
"全員" = "review"
"結局" = "review"
"ほとんど" = "review"
"余裕" = "review"
"腰" = "review"
"必ず" = "review"
"感覚" = "review"
"つい" = "review"
"態度" = "review"
"どうせ" = "review"
"生活" = "review"
"少年" = "review"
"綺麗" = "review"
"いらっしゃる" = "review"
"使う" = "review"
"値段" = "review"
"会計" = "review"
"命" = "review"
"なぜ" = "review"
"口" = "review"
"立ち上がる" = "review"
"もう少し" = "review"
"納得" = "review"
"相変わらず" = "review"
"去年" = "review"
"頂きます" = "review"
"遅い" = "review"
"助かる" = "review"
"どうも" = "review"
"若い" = "review"
"運ぶ" = "review"
"返事" = "review"
"救う" = "review"
"失敗" = "review"
"素直" = "review"
"考え" = "review"
"向く" = "review"
"あまり" = "review"
"相手" = "review"
"落ち着く" = "review"
"怪我" = "review"
"待つ" = "review"
"感情" = "review"
"期待" = "review"
"起こす" = "review"
"捨てる" = "review"
"いっぱい" = "review"
"判断" = "review"
"過去" = "review"
"足" = "review"
"感謝" = "review"
"前" = "review"
"とても" = "review"
"望む" = "review"
"さすが" = "review"
"部屋" = "review"
"寝る" = "review"
"座る" = "review"
"思い出す" = "review"
"今度" = "review"
"返す" = "review"
"壁" = "review"
"弱い" = "review"
"存在" = "review"
"倒れる" = "review"
"内容" = "review"
"おえる" = "review"
"頼む" = "review"
"表情" = "review"
"昨夜" = "review"
"普段" = "review"
"白米" = "review"
"点ける" = "review"
"すぐ" = "review"
"花" = "review"
"両手" = "review"
