[2025-04-18]
"判断" = "learning"
"しばらく" = "review"
"特に" = "review"
"座る" = "learning"
"残る" = "learning"
"突然" = "learning"
"もう少し" = "review"
"若い" = "learning"
"一体" = "review"
"捨てる" = "review"
"相変わらず" = "review"
"どうも" = "review"
"方" = "review"
"去年" = "review"
"黒い" = "review"
"望む" = "review"
"出会う" = "learning"
"やっと" = "review"
"値段" = "learning"
"腰" = "review"
"救う" = "review"
"失敗" = "learning"
"さすが" = "learning"
"普段" = "review"
"存在" = "review"
"返す" = "review"
"頂きます" = "review"
"起こす" = "learning"
"連中" = "learning"
"回る" = "review"
"弱い" = "review"
"前" = "review"
"許す" = "review"
"点ける" = "learning"
"感情" = "review"
"追う" = "learning"
"怪我" = "learning"
"きっと" = "learning"
"口" = "review"
"つく" = "review"
"感謝" = "learning"
"感覚" = "learning"
"残念" = "learning"
"綺麗" = "review"
"つい" = "review"
"遅い" = "review"
"生活" = "review"
